# Generated by Django 4.1 on 2022-08-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
